package constant

const (
	ERROR_MESSAGE_INVALID_PARAMETERS           = "ERROR_MESSAGE_INVALID_PARAMETERS"
	ERROR_MESSAGE_INVALID_USERNAME_OR_PASSWORD = "ERROR_MESSAGE_INVALID_USERNAME_OR_PASSWORD"
	ERROR_MESSAGE_INTERNAL_SERVER_ERROR        = "ERROR_MESSAGE_INTERNAL_SERVER_ERROR"
	ERROR_MESSAGE_USERNAME_ALREADY_EXISTS      = "ERROR_MESSAGE_USERNAME_ALREADY_EXISTS"
	ERROR_MESSAGE_UNAUTHORIZED                 = "ERROR_MESSAGE_UNAUTHORIZED"
	ERROR_MESSAGE_TOKEN_EXPIRED                = "ERROR_MESSAGE_TOKEN_EXPIRED"
)
